In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd 
import numpy as np 
import unicodedata

In [4]:
def remove_accents(name):
    if name is None:
        return None

    normalized = unicodedata.normalize("NFKD", name)
    return "".join(
        char for char in normalized
        if not unicodedata.combining(char)
    )

In [14]:
url = "https://www.basketball-reference.com/leagues/NBA_1950_per_game.html"

In [15]:
player_pg_stats = pd.read_html(url, attrs={"id" : "per_game_stats"})[0]

In [16]:
player_pg_stats["Player"] = player_pg_stats["Player"].apply(remove_accents)

In [17]:
player_pg_stats = player_pg_stats.drop(columns=["Awards", "Rk"])

In [18]:
player_pg_stats.dtypes

Player        str
Age       float64
Team          str
Pos           str
G         float64
FG        float64
FGA       float64
FG%       float64
FT        float64
FTA       float64
FT%       float64
AST       float64
PF        float64
PTS       float64
dtype: object

In [9]:
year=1960
url = f"https://www.basketball-reference.com/leagues/{"NBA" if year >= 1950 else "BAA"}_{year}_advanced.html"
df = pd.read_html(url, attrs={"id" : "advanced"})[0]

In [13]:
df["Player"] = df["Player"].apply(remove_accents)
df = df.drop(columns=["Rk", "Awards"], errors="ignore")
df

,Player,Age,Team,Pos,G,MP,PER,TS%,FTr,OWS,DWS,WS,WS/48
0,Gene Shue,28.0,DET,PG,75.0,3338.0,15.6,0.492,0.360,6.3,2.1,8.5,0.122
1,Wilt Chamberlain,23.0,PHW,C,72.0,3338.0,28.1,0.493,0.429,9.0,8.0,17.0,0.245
2,Bill Russell,25.0,BOS,C,74.0,3146.0,20.2,0.496,0.330,4.9,8.9,13.8,0.211
3,Jack Twyman,25.0,CIN,SF,75.0,3023.0,21.1,0.487,0.369,7.6,0.7,8.3,0.131
4,Bob Pettit,27.0,STL,PF,72.0,2896.0,23.8,0.510,0.473,8.4,3.2,11.5,0.191
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,Brendan McCann,24.0,NYK,PG,4.0,29.0,8.3,0.221,0.300,-0.1,0.0,-0.1,-0.141
120,Jim Ray,26.0,SYR,NaN,4.0,21.0,-3.5,0.167,0.000,-0.1,0.0,-0.1,-0.158
121,Maurice King,24.0,BOS,PG,1.0,19.0,17.3,0.592,0.125,0.1,0.0,0.1,0.264
122,Paul Seymour,32.0,SYR,NaN,4.0,7.0,-17.1,0.000,0.000,-0.1,0.0,-0.1,-0.596
123,League Average,NaN,NaN,NaN,NaN,NaN,NaN,0.464,0.329,NaN,NaN,NaN,NaN

In [15]:
url = "https://www.basketball-reference.com/leagues/NBA_1950_per_game.html"
df = pd.read_html(url, attrs={"id" : "per_game_stats_post"})[0]

In [16]:
df

,Rk,Player,Age,Team,Pos,G,FG,FGA,FG%,FT,FTA,FT%,AST,PF,PTS,Awards
0,1.0,George Mikan,25.0,MNL,C,12.0,10.1,26.3,0.383,11.2,14.2,0.788,3.0,3.9,31.3,NaN
1,2.0,Alex Groza,23.0,INO,NaN,6.0,7.3,12.3,0.595,8.2,9.8,0.831,2.0,3.5,22.8,NaN
2,3.0,Max Zaslofsky,24.0,CHS,SG,2.0,7.5,16.0,0.469,7.5,9.0,0.833,3.0,3.5,22.5,NaN
3,4.0,Don Otten,28.0,WSC,C,2.0,5.0,12.5,0.400,10.5,13.0,0.808,3.0,3.5,20.5,NaN
4,5.0,Jack Nichols,23.0,TRI,PF,3.0,6.0,20.0,0.300,7.7,10.3,0.742,3.7,3.7,19.7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,122.0,Joe Graboski,20.0,CHS,NaN,1.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,NaN
122,123.0,Marshall Hawkins,25.0,INO,NaN,2.0,0.0,0.5,0.000,0.0,0.0,NaN,0.0,0.5,0.0,NaN
123,124.0,Kenny Rollins,26.0,CHS,PG,2.0,0.0,1.5,0.000,0.0,0.0,NaN,0.0,2.0,0.0,NaN
124,125.0,Butch van Breda Kolff,27.0,NYK,NaN,1.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,2.0,0.0,NaN
125,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,0.344,NaN,NaN,0.732,NaN,NaN,NaN,NaN